# Setup
title:       Nguyễn Lê Xuân Bách
tagline:      A responsive theme for your project on GitHub Pages
#baseurl:      ""
#paginate:     1

# About/contact
author:
  name:       Author name
  url:        https://nlxbach.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
